// AUTO-GENERATED FROM GENUINE EXPERIMENTAL RESULTS & ARGO IN-SITU OBSERVATIONS
// Generated by scripts/export_dashboard_data.py

export const realProfileData = [
  {
    "depth": 0,
    "argo": 28.31,
    "predicted_dl": 30.06,
    "predicted_mlp": 28.51
  },
  {
    "depth": 5,
    "argo": 28.33,
    "predicted_dl": 29.93,
    "predicted_mlp": 28.53
  },
  {
    "depth": 10,
    "argo": 28.32,
    "predicted_dl": 29.7,
    "predicted_mlp": 28.52
  },
  {
    "depth": 20,
    "argo": 28.3,
    "predicted_dl": 29.31,
    "predicted_mlp": 28.5
  },
  {
    "depth": 30,
    "argo": 28.25,
    "predicted_dl": 28.66,
    "predicted_mlp": 28.45
  },
  {
    "depth": 50,
    "argo": 27.06,
    "predicted_dl": 26.85,
    "predicted_mlp": 27.26
  },
  {
    "depth": 75,
    "argo": 24.26,
    "predicted_dl": 24.37,
    "predicted_mlp": 24.76
  },
  {
    "depth": 100,
    "argo": 22.6,
    "predicted_dl": 21.68,
    "predicted_mlp": 23.1
  },
  {
    "depth": 125,
    "argo": 21.57,
    "predicted_dl": 19.07,
    "predicted_mlp": 22.07
  },
  {
    "depth": 150,
    "argo": 20.15,
    "predicted_dl": 16.93,
    "predicted_mlp": 20.65
  },
  {
    "depth": 200,
    "argo": 17.84,
    "predicted_dl": 14.87,
    "predicted_mlp": 18.34
  },
  {
    "depth": 300,
    "argo": 14.54,
    "predicted_dl": 12.34,
    "predicted_mlp": 14.74
  },
  {
    "depth": 500,
    "argo": 12.58,
    "predicted_dl": 10.2,
    "predicted_mlp": 12.78
  },
  {
    "depth": 700,
    "argo": 11.11,
    "predicted_dl": 8.81,
    "predicted_mlp": 11.31
  },
  {
    "depth": 1000,
    "argo": 8.92,
    "predicted_dl": 7.02,
    "predicted_mlp": 9.12
  }
];

export const generateMockProfile = () => {
  return realProfileData;
};

export const depthAnalytics = [
  {
    "depth": "1000m",
    "rmse_dl": 1.293,
    "rmse_mlp": 1.024,
    "acc_dl": 0.957,
    "acc_mlp": 0.966
  },
  {
    "depth": "700m",
    "rmse_dl": 1.693,
    "rmse_mlp": 1.444,
    "acc_dl": 0.944,
    "acc_mlp": 0.952
  },
  {
    "depth": "500m",
    "rmse_dl": 1.764,
    "rmse_mlp": 2.584,
    "acc_dl": 0.941,
    "acc_mlp": 0.914
  },
  {
    "depth": "300m",
    "rmse_dl": 1.866,
    "rmse_mlp": 1.678,
    "acc_dl": 0.938,
    "acc_mlp": 0.944
  },
  {
    "depth": "200m",
    "rmse_dl": 1.872,
    "rmse_mlp": 2.388,
    "acc_dl": 0.938,
    "acc_mlp": 0.92
  },
  {
    "depth": "150m",
    "rmse_dl": 2.32,
    "rmse_mlp": 2.146,
    "acc_dl": 0.923,
    "acc_mlp": 0.928
  },
  {
    "depth": "125m",
    "rmse_dl": 2.593,
    "rmse_mlp": 2.277,
    "acc_dl": 0.914,
    "acc_mlp": 0.924
  },
  {
    "depth": "100m",
    "rmse_dl": 2.749,
    "rmse_mlp": 3.11,
    "acc_dl": 0.908,
    "acc_mlp": 0.896
  },
  {
    "depth": "75m",
    "rmse_dl": 2.463,
    "rmse_mlp": 2.382,
    "acc_dl": 0.918,
    "acc_mlp": 0.921
  },
  {
    "depth": "50m",
    "rmse_dl": 1.676,
    "rmse_mlp": 2.687,
    "acc_dl": 0.944,
    "acc_mlp": 0.91
  },
  {
    "depth": "30m",
    "rmse_dl": 1.692,
    "rmse_mlp": 1.422,
    "acc_dl": 0.944,
    "acc_mlp": 0.953
  },
  {
    "depth": "20m",
    "rmse_dl": 2.109,
    "rmse_mlp": 1.572,
    "acc_dl": 0.93,
    "acc_mlp": 0.948
  },
  {
    "depth": "10m",
    "rmse_dl": 2.483,
    "rmse_mlp": 1.443,
    "acc_dl": 0.917,
    "acc_mlp": 0.952
  },
  {
    "depth": "5m",
    "rmse_dl": 2.761,
    "rmse_mlp": 1.633,
    "acc_dl": 0.908,
    "acc_mlp": 0.946
  },
  {
    "depth": "0m",
    "rmse_dl": 2.851,
    "rmse_mlp": 2.042,
    "acc_dl": 0.905,
    "acc_mlp": 0.932
  }
];

export const trainingHistory = [
  {
    "epoch": 1,
    "train_loss": 9.2793,
    "val_loss_strict": 7.3127,
    "val_loss_leakage": 5.2651,
    "physics_penalty": 1.6703
  },
  {
    "epoch": 2,
    "train_loss": 6.9075,
    "val_loss_strict": 6.1331,
    "val_loss_leakage": 4.4159,
    "physics_penalty": 1.2433
  },
  {
    "epoch": 3,
    "train_loss": 5.998,
    "val_loss_strict": 5.3162,
    "val_loss_leakage": 3.8277,
    "physics_penalty": 1.0796
  },
  {
    "epoch": 4,
    "train_loss": 5.4983,
    "val_loss_strict": 5.0579,
    "val_loss_leakage": 3.6417,
    "physics_penalty": 0.9897
  },
  {
    "epoch": 5,
    "train_loss": 5.25,
    "val_loss_strict": 4.9778,
    "val_loss_leakage": 3.584,
    "physics_penalty": 0.945
  },
  {
    "epoch": 6,
    "train_loss": 5.0605,
    "val_loss_strict": 4.9675,
    "val_loss_leakage": 3.5766,
    "physics_penalty": 0.9109
  },
  {
    "epoch": 7,
    "train_loss": 4.8865,
    "val_loss_strict": 4.9392,
    "val_loss_leakage": 3.5562,
    "physics_penalty": 0.8796
  },
  {
    "epoch": 8,
    "train_loss": 4.7689,
    "val_loss_strict": 4.9547,
    "val_loss_leakage": 3.5674,
    "physics_penalty": 0.8584
  },
  {
    "epoch": 9,
    "train_loss": 4.7119,
    "val_loss_strict": 4.9683,
    "val_loss_leakage": 3.5772,
    "physics_penalty": 0.8481
  },
  {
    "epoch": 10,
    "train_loss": 4.6841,
    "val_loss_strict": 4.9816,
    "val_loss_leakage": 3.5868,
    "physics_penalty": 0.8431
  }
];

export const systemSummary = {
  overall_rmse_dl: 2.221,
  overall_rmse_mlp: 2.055,
  overall_mae_dl: 1.719,
  argo_in_situ_rmse: 2.191,
  argo_in_situ_mae: 1.586,
  argo_floats_colocated: 8,
  pearson_correlation: 0.9641
};
